= Snow-World

* link:http://ec2-54-165-213-86.compute-1.amazonaws.com:8080/snow-world/[Snow-World]

== Description

*Snow-World* - rental of snowboards, alpine skis, clothes and all necessary equipment.
In our rental shop you can find equipment and clothes for snowboarding / alpine skiing of the world's leading brands
at good prices. Thanks to our *unique system*, the selection of equipment and clothes can be carried out directly on
the website, for this you need to enter data (height, clothing sizes, shoes, riding style and riding experience).
Also, only here you will be able to view the entire current assortment, including by availability at the moment.
*Snow-World* offers to make an online booking, and free cancellation no later than 1 day before the expected day
of rental.

==== What problem does this project solve or what new does it bring to users?

* online selection all equipment, according to the user's data, because often beginners do not know what is necessary
for comfortable riding;
* search for the current assortment, without visiting the rental salon, so the user
can get acquainted with the current assortment directly on the website using the booking calendar,
and in the absence of the necessary - can do without visiting the rental salon *Snow-World*;
* avoiding queues and wasting time on registration, thanks to a unique online booking system.
Registered users who have experience using the services of *Snow-World* can view the order history,
create a new order based on the previous order

==== Potential users

* beginners who have never been snowboarding/alpine skiing, who want to try
* amateurs who have little riding experience and understand what kind of equipment they need
* professionals who do not have their own equipment/pieces of equipment

*Age category from 3 years

==== Similar Applications

* link:https://www.blueriversports.com/[blueriversports.com, Colorado, USA] +
It offers only sets of equipment, but online booking and prepayment are implemented

* link:https://mountaincreek.snowcloud.store/date/65243842-42b5-4bb2-8197-f0dcec0cb0d9[mountaincreek, New Jersey, USA] +
There is a selection of parameters, online booking and prepayment, but there is no assortment on the website

* link:https://www.val-spirit-rentals.com/rent-equipment/select/ski-male[val-spirit-rentals.com, Les Almes, France] +
Online booking, prepayment, selection by parameters has been implemented, the entire assortment has been added,
users can not see the full set of reserved equipment.

====== Rentals without an online equipment booking system in Belarus

* link:http://www.snowcat.by[SnowCat]
* link:https://afs.by/[Affecta Sport]
* link:https://silichy.by/gornolizhnoe-snaryazhenie-27403[Silichy]

====== Rental with an online booking system of equipment, subject to booking accommodation (package tour)

* link:https://www.ski-planet.com/ru/[Ski-Planet, Alps, France]

====== Rental with an assortment on the website, but without online booking and selection according to user data

* link:https://snowbuddy.by/[SnowBuddy, Minsk, Belarus]
* link:https://sochiskiline.ru/[SkiLine, Sochi, Russia]

==== Competitive advantages

* view the current assortment directly on the website and the opportunity to choose the equipment you like yourself;
* online selection according to the user's specified data;
* online booking
* free cancellation no later than 1 day before the expected date of rental

=== Business analysis

==== User stories

* link:https://miro.com/app/board/uXjVOYKGYS8=/?invite_link_id=755760560023[mind map]

==== UML class diagram

* link:https://github.com/JD2-86/pet-project-zhigalko/blob/master/Snow_World-uml_diagram.drawio[UML diagramm with drawio]

* link:https://github.com/JD2-86/pet-project-zhigalko/blob/master/snow-world-uml-diagram.png[UML diagram .png]