= Snow-World.by

== Description

*Snow-World.by* - аренда сноубордов, горных лыж и необходимой экипировки. В нашем салоне проката можно
найти оборудование и экипировку (далее *экипировка*) для катаний на сноуборде/горных лыж ведущих мировых брендов
по хорошим ценам. Благодаря нашей *уникальной системе* подбор экипировки и оборудования можно осуществить прямо
на сайте, для этого необходимо ввести данные (рост, размеры одежды, обуви, стиль катания и опыт катания).
Также только у нас вы сможете посмотреть весь актуальный ассортимент, в том числе по наличию на текущий момент.
Также *Snow-World.by* предлагает оформить онлайн-бронирование, и бесплатную отмену не позднее чем
за 1 сутки до предполагаемого дня сдачи в аренду.

==== Какую проблему данный проект решает или что нового приносит для пользователей?

* онлайн-подбор, в соответствии с данными пользователя, т.к. часто новички не знают что необходимо для комфортного катания
* просмотр актуального ассортимента, без посещения салон-проката, т.е. на сайте пользователь
может ознакомиться с актуальным ассортиментом, в том числе по наличию на определенную дату (календарь бронирований),
и в случае отсутствия необходимого - может обойтись без посещения салона-проката *Snow-World.by*.
* избежание очередей и траты времени на оформление, благодаря уникальной системе онлайн-бронирования.
Например, лояльные пользователи, которые уже пользовались услугами *Snow-World.by*, могут посмотреть историю заказов,
создать новый заказ на основании прошлого заказа, приходя в *Snow-World.by* по предъявлению кода заказа
подписывают заранее подготовленные документы, получают забронированную экипировку.

==== Потенциальные пользователи

* новички, которые ни разу не катались на сноуборде/горных лыжах, желающие попробовать
* любители, которые имеют небольшой опыт катания и понимают какая экипировка им нужна
* профессионалы, у которых нет своей экипировки/части экипировки

*Возрастная категория от 3 лет

==== Аналогичные приложения

* link:https://www.blueriversports.com/[blueriversports.com, Colorado, USA] +
предлагают только комплекты экипировки, но реализовано онлайн-бронирование и предоплата

* link:https://mountaincreek.snowcloud.store/date/65243842-42b5-4bb2-8197-f0dcec0cb0d9[mountaincreek, New Jersey, USA] +
реализован подбор по параметрам, онлайн-бронирование и предоплата, но ассортимента нет

* link:https://www.val-spirit-rentals.com/rent-equipment/select/ski-male[val-spirit-rentals.com, Ле Лаваше, Франция] +
реализовано онлайн-бронирование, предоплата, подбор по параметрам, добавлен весь ассортимент, нет возможности выбора
и не видишь полный комплект бронируемой экипировки.

====== Прокаты без системы онлайн-бронирования экипировки в Беларуси

* link:http://www.snowcat.by[SnowCat]
* link:https://afs.by/[Affecta Sport]
* link:https://silichy.by/gornolizhnoe-snaryazhenie-27403[Silichy]

====== Прокат с системой онлайн-бронирования экипировки при условии бронирования жилья (пакетный тур)

* link:https://www.ski-planet.com/ru/[Ski-Planet, Альпы, Франция]

====== Прокат с ассортиментом на сайте, но без онлайн-бронирования и подбора по данным пользователя

* link:https://snowbuddy.by/[SnowBuddy, Минск, Беларусь]
* link:https://sochiskiline.ru/[SkiLine, Сочи, Россия]

==== Конкурентное преимущества

* просмотр актуального ассортимента прямо на сайте и возможность выбрать понравившуюся экипировку самостоятельно;
* онлайн-подбор в соответствии с заданными данными пользователя;
* онлайн-бронирование
* бесплатная отмена не позднее чем за 1 сутки до предполагаемого дня сдачи в аренду

=== Business analysis

==== User stories

* link:https://miro.com/app/board/uXjVOYKGYS8=/?invite_link_id=755760560023[mind map]

==== UML class diagram

* link:https://github.com/JD2-86/pet-project-zhigalko/blob/master/Snow_World-uml_diagram.drawio[UML diagramm with drawio]

* link:https://github.com/JD2-86/pet-project-zhigalko/blob/master/snow-world-uml-diagram.png[UML diagram .png]