= ${Snow-World.by}

== Description

*Snow-World.by* - аренда сноубордов, горных лыж и необходимой экипировки. В нашем салоне проката можно
найти оборудование и экипировку (далее *экипировка*) для катаний на сноуборде/горных лыж ведущих мировых брендов
по хорошим ценам. Благодаря нашей *уникальной системе* подбор экипировки и оборудования можно осуществить прямо
на сайте, для этого необходимо ввести данные (рост, размеры одежды, обуви, стиль катания и опыт катания).
Также только у нас вы сможете посмотреть весь актуальный ассортимент, в том числе по наличию на текущий момент.
Также *Snow-World.by* предлагает оформить онлайн-бронирование, и бесплатную отмену не позднее чем
за 1 сутки до предполагаемого дня сдачи в аренду.

==== Какую проблему данный проект решает или что нового приносит для пользователей?

* онлайн-подбор, в соответствии с данными пользователя, т.к. часто новички не знают что необходимо для комфортного катания
* просмотр актуального ассортимента, без приезда в салон-проката, т.е. на сайте пользователь
может ознакомиться с актуальным ассортиментом, в том числе по наличию, и в случае отсутствия необходимого - может
обойтись без приезда.
* избежание очередей, благодаря онлайн-бронированию, предоплате, получения кода заказа, предъявлению в салоне-проката.
Например, лояльные пользователи, которые уже пользовались услугами *Snow-World.by*, вероятно знают экипировку,
которая им нужна.+


==== Потенциальные пользователи

* Пункт 1
* Пункт 2
* ...
* Пункт N

==== Аналогичные приложения

* Пункт 1
* Пункт 2
* ...
* Пункт N

==== Конкурентное преимущество

* просмотр актуального ассортимента прямо на сайте;
* онлайн-подбор в соответствии с заданными данными пользователя;
* онлайн-бронирование
* бесплатная отмену не позднее чемза 1 сутки до предполагаемого дня сдачи в аренду